import { Event, EventHost } from './eventTypes';

// Mock event hosts
const hosts: EventHost[] = [
  {
    id: 'h1',
    name: 'Tech Conference Global',
    verified: true,
  },
  {
    id: 'h2',
    name: 'University of Innovation',
    verified: true,
  },
  {
    id: 'h3',
    name: 'Creative Arts Foundation',
    verified: false,
  },
  {
    id: 'h4',
    name: 'Sports League International',
    verified: true,
  },
  {
    id: 'h5',
    name: 'Professional Network Hub',
    verified: true,
  },
  {
    id: 'h6',
    name: 'Skills Workshop Academy',
    verified: false,
  },
];

// Mock events
export const mockEvents: Event[] = [
  {
    id: 'e1',
    title: 'AI & Machine Learning Summit 2025',
    shortDescription: 'Join industry leaders discussing the future of AI',
    description: 'A comprehensive summit bringing together AI researchers, practitioners, and enthusiasts. Learn about the latest developments in machine learning, deep learning, and artificial intelligence applications across industries.',
    date: '2025-01-15',
    time: '09:00 AM',
    endTime: '05:00 PM',
    location: 'Online',
    locationType: 'Online',
    category: 'Academic',
    host: hosts[0],
    bannerColor: '#667eea',
    bannerIcon: 'hardware-chip-outline',
    attendeeCount: 1247,
    maxAttendees: 2000,
    isBookmarked: false,
    hasRSVPd: false,
  },
  {
    id: 'e2',
    title: 'Startup Networking Mixer',
    shortDescription: 'Connect with founders, investors, and innovators',
    description: 'An evening of networking with startup founders, angel investors, and venture capitalists. Perfect opportunity to pitch your ideas, find co-founders, or discover investment opportunities.',
    date: '2025-01-08',
    time: '06:00 PM',
    endTime: '09:00 PM',
    location: 'San Francisco, CA',
    locationType: 'In-Person',
    category: 'Networking',
    host: hosts[4],
    bannerColor: '#f093fb',
    bannerIcon: 'people-outline',
    attendeeCount: 156,
    maxAttendees: 200,
    isBookmarked: true,
    hasRSVPd: false,
  },
  {
    id: 'e3',
    title: 'Digital Art Exhibition 2025',
    shortDescription: 'Explore the intersection of art and technology',
    description: 'Experience cutting-edge digital art from artists around the world. This exhibition showcases NFT art, generative art, VR experiences, and interactive installations.',
    date: '2025-01-20',
    time: '10:00 AM',
    endTime: '08:00 PM',
    location: 'New York, NY',
    locationType: 'In-Person',
    category: 'Cultural',
    host: hosts[2],
    bannerColor: '#fa709a',
    bannerIcon: 'color-palette-outline',
    attendeeCount: 892,
    maxAttendees: 1500,
    isBookmarked: false,
    hasRSVPd: false,
  },
  {
    id: 'e4',
    title: 'React Native Workshop',
    shortDescription: 'Build mobile apps with React Native',
    description: 'Hands-on workshop covering React Native fundamentals, navigation, state management, and deployment. Perfect for web developers looking to build mobile apps.',
    date: '2025-01-12',
    time: '02:00 PM',
    endTime: '06:00 PM',
    location: 'Online',
    locationType: 'Online',
    category: 'Workshops',
    host: hosts[5],
    bannerColor: '#4facfe',
    bannerIcon: 'code-slash-outline',
    attendeeCount: 234,
    maxAttendees: 300,
    isBookmarked: true,
    hasRSVPd: true,
  },
  {
    id: 'e5',
    title: 'Annual Marathon 2025',
    shortDescription: 'Run for a cause - charity marathon event',
    description: 'Join thousands of runners in our annual charity marathon. All proceeds go to local education initiatives. Multiple distance options: 5K, 10K, Half Marathon, and Full Marathon.',
    date: '2025-02-01',
    time: '06:00 AM',
    endTime: '12:00 PM',
    location: 'Los Angeles, CA',
    locationType: 'In-Person',
    category: 'Sports',
    host: hosts[3],
    bannerColor: '#43e97b',
    bannerIcon: 'fitness-outline',
    attendeeCount: 3421,
    maxAttendees: 5000,
    isBookmarked: false,
    hasRSVPd: false,
  },
  {
    id: 'e6',
    title: 'Product Management Masterclass',
    shortDescription: 'Learn from top product leaders',
    description: 'A comprehensive masterclass on product management covering strategy, roadmapping, user research, and stakeholder management. Includes case studies from leading tech companies.',
    date: '2025-01-18',
    time: '01:00 PM',
    endTime: '05:00 PM',
    location: 'Online',
    locationType: 'Online',
    category: 'Workshops',
    host: hosts[5],
    bannerColor: '#764ba2',
    bannerIcon: 'bulb-outline',
    attendeeCount: 567,
    maxAttendees: 800,
    isBookmarked: false,
    hasRSVPd: false,
  },
  {
    id: 'e7',
    title: 'Jazz Night Live',
    shortDescription: 'An evening of smooth jazz and soul',
    description: 'Enjoy live performances from renowned jazz musicians. Food and drinks available. A perfect evening to unwind and enjoy great music.',
    date: '2025-01-25',
    time: '07:00 PM',
    endTime: '11:00 PM',
    location: 'Chicago, IL',
    locationType: 'In-Person',
    category: 'Cultural',
    host: hosts[2],
    bannerColor: '#ff6b6b',
    bannerIcon: 'musical-notes-outline',
    attendeeCount: 178,
    maxAttendees: 250,
    isBookmarked: false,
    hasRSVPd: false,
  },
  {
    id: 'e8',
    title: 'Blockchain & Web3 Conference',
    shortDescription: 'Exploring decentralized technologies',
    description: 'Deep dive into blockchain technology, cryptocurrencies, DeFi, and Web3 applications. Network with developers, investors, and blockchain enthusiasts.',
    date: '2025-01-22',
    time: '09:00 AM',
    endTime: '06:00 PM',
    location: 'Austin, TX',
    locationType: 'In-Person',
    category: 'Academic',
    host: hosts[0],
    bannerColor: '#f857a6',
    bannerIcon: 'link-outline',
    attendeeCount: 689,
    maxAttendees: 1000,
    isBookmarked: true,
    hasRSVPd: false,
  },
  {
    id: 'e9',
    title: 'Women in Tech Meetup',
    shortDescription: 'Empowering women in technology',
    description: 'Monthly meetup for women in tech to network, share experiences, and support each other. Featuring panel discussions, mentorship opportunities, and career advice.',
    date: '2025-01-10',
    time: '06:30 PM',
    endTime: '09:00 PM',
    location: 'Seattle, WA',
    locationType: 'In-Person',
    category: 'Networking',
    host: hosts[4],
    bannerColor: '#a8edea',
    bannerIcon: 'people-circle-outline',
    attendeeCount: 234,
    maxAttendees: 300,
    isBookmarked: false,
    hasRSVPd: false,
  },
  {
    id: 'e10',
    title: 'Basketball Tournament Finals',
    shortDescription: 'Championship game - don\'t miss it!',
    description: 'The final showdown of our annual basketball tournament. Watch the top teams compete for the championship trophy. Food trucks, entertainment, and prizes!',
    date: '2025-01-28',
    time: '03:00 PM',
    endTime: '07:00 PM',
    location: 'Miami, FL',
    locationType: 'In-Person',
    category: 'Sports',
    host: hosts[3],
    bannerColor: '#ff9a56',
    bannerIcon: 'basketball-outline',
    attendeeCount: 1523,
    maxAttendees: 2500,
    isBookmarked: false,
    hasRSVPd: false,
  },
];
